FROM flink:1.18.1-scala_2.12-java11

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /requirements.txt
RUN pip3 install --no-cache-dir -r /requirements.txt
RUN pip3 install --no-cache-dir psycopg2-binary
RUN pip3 install --no-cache-dir apache-flink
RUN rm /requirements.txt

USER flink